"use strict";var e=require("@ethersproject/logger"),r=require("../errors.js"),t=require("../errors-3fxlG6WB.js");require("ofetch");class s extends r.PrivyConnectorError{constructor(){super("Wallet timeout"),this.type="wallet_error"}}class o extends r.PrivyConnectorError{constructor(){super("User rejected connection"),this.type="wallet_error"}}class n extends r.PrivyError{constructor(e,r,t){super(e),this.type="provider_error",this.code=r,this.data=t}}class a extends n{constructor(e){super(e.message,e.code,e.data);let r=Object.values(t.n).find((r=>r.eipCode===e.code));this.details=r||t.n.UNKNOWN_ERROR,-32002===e.code&&(e.message?.includes("already pending for origin")?e.message?.includes("wallet_requestPermissions")?this.details=t.n.E32002_CONNECTION_ALREADY_PENDING:this.details=t.n.E32002_REQUEST_ALREADY_PENDING:e.message?.includes("Already processing")&&e.message.includes("eth_requestAccounts")&&(this.details=t.n.E32002_WALLET_LOCKED))}}const i={ERROR_USER_EXISTS:{message:"User already exists for this address",detail:"Try another address!",retryable:!1},ERROR_TIMED_OUT:{message:"Wallet request timed out",detail:"Please try connecting again.",retryable:!0},ERROR_WALLET_CONNECTION:{message:"Could not log in with wallet",detail:"Please try connecting again.",retryable:!0},ERROR_USER_REJECTED_CONNECTION:{message:"You rejected the request",detail:"Please try connecting again.",retryable:!0},ERROR_USER_LIMIT_REACHED:{message:"Unable to link",detail:"You've reached the maximum number of linked wallets.",retryable:!1},...t.n};exports.ConnectorErrors=i,exports.PrivyProviderRpcError=a,exports.ProviderRpcError=n,exports.UserRejectedConnectionError=o,exports.WalletTimeoutError=s,exports.formatConnectorError=s=>{if(s instanceof r.PrivyConnectorError)return s;if(s?.code&&s?.reason){let r=new a(s);return s.code===e.ErrorCode.ACTION_REJECTED&&(r.details=t.n.E4001_USER_REJECTED_REQUEST),r}return s?.code?new a(s):new r.PrivyConnectorError("Unknown connector error",s)};
